### ISSUE TITLE
Issue with Reproduction

### ISSUE THREAD

**Issue by tangzhy** [RowitZou/DC-Match#1]
Hi, we try and reproduce your results.

The f1 metrics of roberta-base are listed as follows using your released command and data:

For medical-sm,  base=0.7209, dc-match=0.7145
For mrpc,  base=0.9052, dc-match=0.9032

Will your explain any insight on this, since no improvement is observed? or is there model checkpoint available?

Best,
Zhengyang

**Comment by RowitZou** [comment]
Hi, there. We reported our results with top-3 checkpoints averaged, as described in the paper. 

The training procedure is duplicated multiple times with different seeds for small datasets. We observed the performance fluctuation on these small datasets, but the average results are better.

The more training data we have, the more stable trends we can observe. For example, QQP has nearly 400K training data, and its performance is more stable and easier to reproduce our results.
